# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://127.0.0.1:3306/diary # Database이름 ?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: root
    password: 1111
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  session:
    store-type: redis # 세션 저장소를 지정합니다.
    redis:
      namespace: server:session # 세션을 저장하는 데 사용되는 키의 네임스페이스를 지정합니다.

  data:
    redis:
      host: localhost
      port: 6379
      database: 0